---
header-includes:
- \usepackage{amssymb,amsthm,amsmath}
- \usepackage{mathtools}
output: pdf_document
---

# Review of Literature -
## File:Lit Review 3{#litReview3}Characteristics of the FSU pop
------------------------------

Theories of Immigration
-----------------------

Economic Stuff
--------------

Policy of Absorbtion
--------------------

### "Israel as a Returning Diaspora"

nice recent paper with good overviews
[Amit-Returning](file:///Users/AbuDavid/Documents/ThesisDocs/Amit, Semyonov/2006/Amit, Semyonov - Metropolis world bulletin - 2006.pdf)

### "Ethnic Stratification in Israel"

There was good stuff in Bar-Chaim
[Bar-Chaim](file:///Users/AbuDavid/Documents/ThesisDocs/Bar-haim, Semyonov/2015/Bar-haim, Semyonov - The International Handbook of the Demography of Race and Ethnicity - 2015.pdf)
timing: 1989 collapse of FSU -&gt; influx of immigrants to Israel.

### "Migration Patterns to and from Israel"

### "Self-Selection in moving to US or IL"

-   autocite:Cohen2007a [cohen Self
    Selection](file:///Users/AbuDavid/Documents/ThesisDocs/Cohen, Haberfeld/2007/Cohen, Haberfeld - SELF-SELECTION AND EARNINGS ASSIMILATION IMMIGRANTS FROM THE FORMER SOVIET UNION IN ISRAEL AND THE UNITED STATES - 20.pdf)
    different destination countries have different returns to skills
    -p.650

US granted refugee status to J. from FSU until 1989 - what about exit
visa from Soviet Union?

after 1989 - family reunification visa to USA, but didn't other article
say this was earlier?

skilled immigrants go to countries with high returns to skills,
low-skilled (less skilled) prefer social safety net countries

compare rate of earnings growth for FSU immigrants v. US natives and IL
natives of similar demographics

1.  2 asumptions

    1.  skills are equally transferable
        -   non-native speaker
        -   advanced economies in IL and US

    2.  FSU immigrants are treated equally by US and IL labor markets

2.  2 waves of immigration = 1.8 Million J. + family members

    1.  1968- early 80s 350k
    2.  late

### TODO Cohen 2009 - Migration Patterns to and from Israel

autocite:cohen2009 has exported highlights [@cohen2009 115] [The
pdf](file:///Users/AbuDavid/Documents/ThesisDocs/Cohen/2009/Cohen - Migration Patterns to and from Israel - 2009.pdf)
these notes are in the file notes.org

1.  success of Z.

    1.  % of world J. in IL
    2.  % J. v. A. in IL
    3.  pop. growth rate of J. in IL

2.  p\. 119 - 350k emigrants from IL, 1/2 in US

    CBS \# of 480k includes IL Arabs, approx. 100k 2003 ministry of
    absorbtion said 700k

    -   didn't account for mortality abroad

3.  rater of return migration are higher than most other sending
    countries

    -   not every IL who abroad for 1 yr will never come backend

4.  what is a good indicator for skills?

    -   emigrants return better educated than when they left
    -   but those w/ higher income stay in US, lower return

5.  FSU !!!

    1.  1st wave 400k 1989-1991
        -   400k immigrants to IL
        -   high schooling - 14 yrs

    2.  then, up to 2000 (after 1992)
        -   60k to 80k annually
        -   only 13 yrs schooling

    3.  conclusion
        -   in post 1991, higher edu. seek USA CANADA recently Germany
            -   in 2002 22k FSU J. &gt; IL or US

6.  impact of second intifada

    decline since 1999 -18k in 2007 -13k 2008 from 77k in 1999

    increase in *annual emigration* (emigrants minus returnees)
















